### ISSUE TITLE
Alibaba: ability to exclude some default tags (Alibaba Images can only have 20 Tags)

### ISSUE THREAD

**Issue by amolari** [f5devcentral/f5-bigip-image-generator#34]
**Is your feature request related to a problem? Please describe.**
We need to add a few tags to the Alibaba Image/Snapshot. This is done with the IMAGE_TAGS property in the config files.
However, the tool generate already 19 Tags. Alibaba supports up to 20 Tags for the Image and Snapshot, so we miss a couple of tags we require.
Could you add the option to exclude some of the default tags? This way we have "space" for our few additional custom tags.

**Describe the solution you'd like**
New option "EXCLUDE_TAGS" which accept a list of Tag keys. All configured keys in this list will be excluded from the AddTag operation for the Image/AMI and Snapshot.

**Additional context**

**Comment by kmaloney** [comment]
Agreed.  That doesn't make IMAGE_TAGS parameter very useful in Alibaba.  It doesn't appear that there is an associated (adjustable) quota for this, but regardless, being able to remove tags you don't find useful seems like a good feature.

To aid other users in finding this parameter in documentation, we plan to put EXCLUDE at the end of the name (rather than the beginning per your suggestion). This naming would result in both IMAGE_TAGS and IMAGE_TAGS_EXCLUDE appearing in the same place in the parameter list table.

Config would look like:

IMAGE_TAGS_EXCLUDE:
- build_source
- build_type
- version_basebuild
- version_build
- version_edition
- version_version

Keys included in IMAGE_TAGS_EXCLUDE that don't exist in the tags list will be ignored (with a log message).

This issue is being tracked internally with VECLOUD-1273.

**Comment by kmaloney** [comment]
Resolved in v1.16.   Use IMAGE_TAGS_EXCLUDE to exclude a list of tags per [updated user guide](https://github.com/f5devcentral/f5-bigip-image-generator#user-guide).
